# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fkie_multimaster_msgs/grpc/screen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fkie_multimaster_msgs/grpc/screen.proto',
  package='fkie_multimaster_msgs.screen',
  syntax='proto3',
  serialized_pb=_b('\n\'fkie_multimaster_msgs/grpc/screen.proto\x12\x1c\x66kie_multimaster_msgs.screen\"\x07\n\x05\x45mpty\"@\n\x07Screens\x12\x35\n\x07screens\x18\x01 \x03(\x0b\x32$.fkie_multimaster_msgs.screen.Screen\"$\n\x06Screen\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\"\x16\n\x05Nodes\x12\r\n\x05nodes\x18\x01 \x03(\t\"\x17\n\x07\x44irSize\x12\x0c\n\x04size\x18\x01 \x01(\x03\x32\x8d\x05\n\rScreenService\x12Y\n\nGetScreens\x12$.fkie_multimaster_msgs.screen.Screen\x1a%.fkie_multimaster_msgs.screen.Screens\x12[\n\rGetAllScreens\x12#.fkie_multimaster_msgs.screen.Empty\x1a%.fkie_multimaster_msgs.screen.Screens\x12`\n\x12GetMultipleScreens\x12#.fkie_multimaster_msgs.screen.Empty\x1a%.fkie_multimaster_msgs.screen.Screens\x12T\n\x08RosClean\x12#.fkie_multimaster_msgs.screen.Empty\x1a#.fkie_multimaster_msgs.screen.Empty\x12U\n\tDeleteLog\x12#.fkie_multimaster_msgs.screen.Nodes\x1a#.fkie_multimaster_msgs.screen.Empty\x12\\\n\x0eGetLogDiskSize\x12#.fkie_multimaster_msgs.screen.Empty\x1a%.fkie_multimaster_msgs.screen.DirSize\x12W\n\x0bWipeScreens\x12#.fkie_multimaster_msgs.screen.Empty\x1a#.fkie_multimaster_msgs.screen.Emptyb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='fkie_multimaster_msgs.screen.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=80,
)


_SCREENS = _descriptor.Descriptor(
  name='Screens',
  full_name='fkie_multimaster_msgs.screen.Screens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='screens', full_name='fkie_multimaster_msgs.screen.Screens.screens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=146,
)


_SCREEN = _descriptor.Descriptor(
  name='Screen',
  full_name='fkie_multimaster_msgs.screen.Screen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fkie_multimaster_msgs.screen.Screen.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node', full_name='fkie_multimaster_msgs.screen.Screen.node', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=184,
)


_NODES = _descriptor.Descriptor(
  name='Nodes',
  full_name='fkie_multimaster_msgs.screen.Nodes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='fkie_multimaster_msgs.screen.Nodes.nodes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=208,
)


_DIRSIZE = _descriptor.Descriptor(
  name='DirSize',
  full_name='fkie_multimaster_msgs.screen.DirSize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='fkie_multimaster_msgs.screen.DirSize.size', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=233,
)

_SCREENS.fields_by_name['screens'].message_type = _SCREEN
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Screens'] = _SCREENS
DESCRIPTOR.message_types_by_name['Screen'] = _SCREEN
DESCRIPTOR.message_types_by_name['Nodes'] = _NODES
DESCRIPTOR.message_types_by_name['DirSize'] = _DIRSIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'fkie_multimaster_msgs.grpc.screen_pb2'
  # @@protoc_insertion_point(class_scope:fkie_multimaster_msgs.screen.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Screens = _reflection.GeneratedProtocolMessageType('Screens', (_message.Message,), dict(
  DESCRIPTOR = _SCREENS,
  __module__ = 'fkie_multimaster_msgs.grpc.screen_pb2'
  # @@protoc_insertion_point(class_scope:fkie_multimaster_msgs.screen.Screens)
  ))
_sym_db.RegisterMessage(Screens)

Screen = _reflection.GeneratedProtocolMessageType('Screen', (_message.Message,), dict(
  DESCRIPTOR = _SCREEN,
  __module__ = 'fkie_multimaster_msgs.grpc.screen_pb2'
  # @@protoc_insertion_point(class_scope:fkie_multimaster_msgs.screen.Screen)
  ))
_sym_db.RegisterMessage(Screen)

Nodes = _reflection.GeneratedProtocolMessageType('Nodes', (_message.Message,), dict(
  DESCRIPTOR = _NODES,
  __module__ = 'fkie_multimaster_msgs.grpc.screen_pb2'
  # @@protoc_insertion_point(class_scope:fkie_multimaster_msgs.screen.Nodes)
  ))
_sym_db.RegisterMessage(Nodes)

DirSize = _reflection.GeneratedProtocolMessageType('DirSize', (_message.Message,), dict(
  DESCRIPTOR = _DIRSIZE,
  __module__ = 'fkie_multimaster_msgs.grpc.screen_pb2'
  # @@protoc_insertion_point(class_scope:fkie_multimaster_msgs.screen.DirSize)
  ))
_sym_db.RegisterMessage(DirSize)



_SCREENSERVICE = _descriptor.ServiceDescriptor(
  name='ScreenService',
  full_name='fkie_multimaster_msgs.screen.ScreenService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=236,
  serialized_end=889,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetScreens',
    full_name='fkie_multimaster_msgs.screen.ScreenService.GetScreens',
    index=0,
    containing_service=None,
    input_type=_SCREEN,
    output_type=_SCREENS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllScreens',
    full_name='fkie_multimaster_msgs.screen.ScreenService.GetAllScreens',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SCREENS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMultipleScreens',
    full_name='fkie_multimaster_msgs.screen.ScreenService.GetMultipleScreens',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SCREENS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RosClean',
    full_name='fkie_multimaster_msgs.screen.ScreenService.RosClean',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteLog',
    full_name='fkie_multimaster_msgs.screen.ScreenService.DeleteLog',
    index=4,
    containing_service=None,
    input_type=_NODES,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLogDiskSize',
    full_name='fkie_multimaster_msgs.screen.ScreenService.GetLogDiskSize',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DIRSIZE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WipeScreens',
    full_name='fkie_multimaster_msgs.screen.ScreenService.WipeScreens',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCREENSERVICE)

DESCRIPTOR.services_by_name['ScreenService'] = _SCREENSERVICE

# @@protoc_insertion_point(module_scope)
