(cl:defpackage fkie_multimaster_msgs-srv
  (:use )
  (:export
   "DISCOVERMASTERS"
   "<DISCOVERMASTERS-REQUEST>"
   "DISCOVERMASTERS-REQUEST"
   "<DISCOVERMASTERS-RESPONSE>"
   "DISCOVERMASTERS-RESPONSE"
   "GETSYNCINFO"
   "<GETSYNCINFO-REQUEST>"
   "GETSYNCINFO-REQUEST"
   "<GETSYNCINFO-RESPONSE>"
   "GETSYNCINFO-RESPONSE"
   "LOADLAUNCH"
   "<LOADLAUNCH-REQUEST>"
   "LOADLAUNCH-REQUEST"
   "<LOADLAUNCH-RESPONSE>"
   "LOADLAUNCH-RESPONSE"
   "TASK"
   "<TASK-REQUEST>"
   "TASK-REQUEST"
   "<TASK-RESPONSE>"
   "TASK-RESPONSE"
  ))

